title: Meine Website
description: Eine einfache GitHub Pages Seite mit Jekyll
theme: jekyll-theme-cayman

# Navigationseintr√§ge
nav:
  - name: Start
    link: /achimswebsite/
  - name: Research
    link: /achimswebsite/research
  - name: CV
    link: /achimswebsite/CV
